### ISSUE TITLE
Problems with multiplayer

### ISSUE THREAD

**Issue by feytox** [feytox/Etherology#5]
По каким-то причинам выкидывает "соединение потеряно".
https://discord.com/channels/1004036886739828786/1004092548425453648/1309155559370395708 (PawDevs server)

**Comment by feytox** [comment]
https://discord.com/channels/1004036886739828786/1004040051778408579/1320145924210692239

**Comment by dekert33** [comment]
I have a similar problem. The game works, the dedicated server works, but you cannot connect due to a lost connection. And there is almost nothing in the logs beside this: 

> [13:55:11] [Server thread/INFO]: com.mojang.authlib.GameProfile@41d52e07[id=xxx-xxx-xxx-xxx-xxx,name=XXX,properties={}] lost connection: Timed out [13:55:11] [Server thread/WARN]: handleDisconnection() called twice

**Comment by feytox** [comment]
https://discord.com/channels/1004036886739828786/1004040051778408579/1323331928711233621

**Comment by feytox** [comment]
Possibly fixed in 5bf589b (0.1.6)

**Comment by SkullHunter** [comment]
It still occurs unfortunately, 1.6 didn't fix it :( I'm now playing on 1.7 and i'm getting the same issue
